---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src1: index1.html
        dest1: /var/www/html/html/
        src1: styles.css
        dest1: /var/www/html/html/
        src1: images/
        dest1: /var/www/html/html/
...
